import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { SimpleAnalytics } from '@/components/SimpleAnalytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SimpleAnalytics
          enabled={true}
          ignorePages={['/admin/*', '/account/*']}
          collectEvents={['downloads', 'outbound']}
          downloadExtensions={['pdf', 'csv', 'docx']}
          customSettings={{
            collectDarkMode: true,
          }}
        >
          {children}
        </SimpleAnalytics>
      </body>
    </html>
  );
}